### ISSUE TITLE
NBT

### ISSUE THREAD

**Issue by AechtRob** [codetaylor/dropt-bed#1]
Awesome addon. A few issues I can't work out.....

1) Is this a new item/block, so if I need to refer to this new item/block in other mods does it need referring to as dropt-bed:bed or still as minecraft:bed ?

2) Does the bed still respect the vanilla variants like colour, orientation and head/foot? I'm also wondering whether I'll need to run some world-gen script to replace all beds generated during world gen, and that will mean I need to supply all the variant data for the replacements too, if it's a literal different block.

3) I can't actually get it to work :) I have this as the first rule in my Dropt main config:

```
{
      "match": {
        "drops": {
          "drops": [
		  "minecraft:bed:*"
          ]
        }
      },
      "replaceStrategy": "REPLACE_ITEMS",
      "drops": [{"minecraft:brown_mushroom"}]
    }
```

But placing and then breaking a bed still drops a bed (the bed first turns red, then breaks as normal, dropping the same colour bed as was there at first). Same result if I swap "drops" for "blocks". Have I misunderstood something?

**Comment by codetaylor** [comment]
1. It is not new, it overrides `minecraft:bed`.
2. It behaves exactly like the vanilla bed, no need to do anything special.
3. The json is incorrect, try this instead:

```json
{
  "rules": [
    {
      "debug": true,
      "match": {
        "drops": {
          "drops": [
            "minecraft:bed:*"
          ]
        }
      },
      "replaceStrategy": "REPLACE_ITEMS",
      "drops": [
        {
          "item": {
            "items": [
              "minecraft:brown_mushroom"
            ]
          }
        }
      ]
    }
  ]
}
```

**Comment by AechtRob** [comment]
Ah sorry - my replacement was wrongly done! Thanks. That works nicely.

Bed still turn red before breaking, but I an live with that for the ability to bin two additional mods form a pack.
