### ISSUE TITLE
Exploding a bed

### ISSUE THREAD

**Issue by AechtRob** [codetaylor/dropt-bed#2]
Exploding a bed (eg. with vanilla TNT) seems to still drop a bed as an item, rather than the newly configged drops. Example json attached. These drops work fine when broken by a player, not when exploded. Even adding a harvester as explicitly an explosion does not cause an exploded bed to drop the new items.

[drops.json.txt](https://github.com/codetaylor/dropt-bed/files/4581647/drops.json.txt)

**Comment by codetaylor** [comment]
Should be fixed in `1.0.1`
